import 'package:flutter/material.dart';
const Color blue = Color(0xff347af0);
const Color blueAc = Color(0xffe0e9f8);
const Color primary = Color(0xff485068);
const Color white = Color(0xffffffff);
const Color black = Color(0xff000000);
const Color grey = Color(0xffBDBDBD);
const Color greyAc = Color(0xffF5F6F9);
const Color orange = Color(0xffffac30);
const Color dot = Color(0xffedf1f9);